# Generated by Django 3.2.5 on 2021-07-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='Message',
        ),
    ]
