# Generated by Django 3.2.5 on 2021-07-18 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('repo_language', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('repo_primary_lang', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('repo_is_private', models.BooleanField(default=False)),
                ('repo_license', models.CharField(blank=True, max_length=70, null=True)),
                ('repo_last_checked_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
            options={
                'unique_together': {('repo_name', 'repo_language')},
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_name', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('dependency_language', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('dependency_license', models.CharField(blank=True, max_length=70, null=True)),
                ('license_last_checked_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
            options={
                'unique_together': {('dependency_name', 'dependency_language')},
            },
        ),
    ]
