# Generated by Django 3.2.5 on 2021-07-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20210718_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanned_repo',
            name='repo_last_checked_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
