# Generated by Django 3.2.5 on 2021-08-02 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_alter_repo_dependency_pair_date_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanned_repo',
            name='repo_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
