# Generated by Django 3.2.5 on 2021-08-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_scanned_repo_repo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanned_repo',
            name='repo_scan_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanned_repo',
            name='repo_scan_error_message',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
    ]
