# Generated by Django 3.2.9 on 2021-12-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_alter_scanned_repo_repo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanned_repo',
            name='repo_scan_status',
            field=models.CharField(blank=True, default='none', max_length=20, null=True),
        ),
    ]
