# Generated by Django 3.2.9 on 2021-12-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_scanned_repo_repo_scan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanned_repo',
            name='repo_scan_status',
            field=models.CharField(blank=True, default='none', max_length=20, null=True),
        ),
    ]
